theme: jekyll-theme-minimal
title: Joan Domingo Sallent
description: Hi there! Welcome to my personal website. You'll find here some of my side projects. Enjoy!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme